/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alejo
 */
public class PrestamoX extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrestamoX.class.getName());

    private double credito;
    private int periodoMax, periodoMin;
    private double interesMin, interesMax;
    private double incremento;
    private int tiposIntrs, añosMeses;
    private double pagoMensual;
    private boolean tablaPagos = false;

    private javax.swing.JTable jtablaPrestamo;
    private javax.swing.JTable jtablaCabsFilas;

    /**
     * Creates new form PrestamoX
     */
    public PrestamoX() {
        initComponents();
        setLocationRelativeTo(null);

        // Vincular eventos de botones
        jbtCalculoPagos.addActionListener(evt -> jbtCalculoPagosActionPerformed(evt));
        jbtCalculoAmort.addActionListener(evt -> jbtCalculoAmortActionPerformed(evt));
        jbtCalculoAmort.setEnabled(false);

        // Vincular eventos del menú
        jmItemInstruc.addActionListener(evt -> jmItemInstrucActionPerformed(evt));
        jmItemSalir.addActionListener(evt -> jmItemSalirActionPerformed(evt));
        jmItemAños.addActionListener(evt -> jmItemAñosMesesActionPerformed(evt));
        jmItemMeses.addActionListener(evt -> jmItemAñosMesesActionPerformed(evt));
        jmItemAcercaDe.addActionListener(evt -> jmItemAcercaDeActionPerformed(evt));

        // Configuración inicial de la interfaz
        jmItemAños.setEnabled(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Años del prestamo"));

        // Inicializar tabla base
        initTable(18, 5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfCredito = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfPeriodoMax = new javax.swing.JTextField();
        jtfPeriodoMin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfInteresMax = new javax.swing.JTextField();
        jtfInteresMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbIncremento = new javax.swing.JComboBox<>();
        jbtCalculoPagos = new javax.swing.JButton();
        jbtCalculoAmort = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jmbarBarraDeMenus = new javax.swing.JMenuBar();
        jmnuOpciones = new javax.swing.JMenu();
        jmItemInstruc = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmItemSalir = new javax.swing.JMenuItem();
        jmnuPrestamoEn = new javax.swing.JMenu();
        jmItemAños = new javax.swing.JMenuItem();
        jmItemMeses = new javax.swing.JMenuItem();
        jmnuAyuda = new javax.swing.JMenu();
        jmItemAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Credito:");

        jtfCredito.setText("6000");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Maximo");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Minimo");

        jtfPeriodoMax.setText("18");

        jtfPeriodoMin.setText("1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jtfPeriodoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPeriodoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("% Maximo");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("% Minimo");

        jtfInteresMax.setText("10.00");

        jtfInteresMin.setText("1");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Incremento");

        jcbIncremento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.10", "0.25", "0.50", "1.00" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jtfInteresMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfInteresMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jbtCalculoPagos.setText("Pagos");

        jbtCalculoAmort.setText("Amortizacion");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jmnuOpciones.setText("Opciones");
        jmnuOpciones.setToolTipText("O");

        jmItemInstruc.setText("Instrucciones");
        jmnuOpciones.add(jmItemInstruc);
        jmnuOpciones.add(jSeparator1);

        jmItemSalir.setText("Salir");
        jmnuOpciones.add(jmItemSalir);

        jmbarBarraDeMenus.add(jmnuOpciones);

        jmnuPrestamoEn.setText("Prestamo en...");
        jmnuPrestamoEn.setToolTipText("P");

        jmItemAños.setText("Años");
        jmnuPrestamoEn.add(jmItemAños);

        jmItemMeses.setText("Meses");
        jmnuPrestamoEn.add(jmItemMeses);

        jmbarBarraDeMenus.add(jmnuPrestamoEn);

        jmnuAyuda.setText("Ayuda");
        jmnuAyuda.setToolTipText("A");

        jmItemAcercaDe.setText("Acerca de...");
        jmnuAyuda.add(jmItemAcercaDe);

        jmbarBarraDeMenus.add(jmnuAyuda);

        setJMenuBar(jmbarBarraDeMenus);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jbtCalculoPagos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbtCalculoAmort)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtfCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCalculoPagos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtCalculoAmort)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitForm(java.awt.event.WindowEvent evt) {
        System.exit(0);
    }

    private void jmItemSalirActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void jmItemInstrucActionPerformed(java.awt.event.ActionEvent evt) {
        String mensaje = "Introduzca el credito, la duracion del prestamo y el tipo\n"
                + "de interes. Pulse el boton [Pagos] para visualizar\n"
                + "los pagos mensuales en la rejilla.\n\n"
                + "Elija un pago mensual y pulse el boton [Amortizacion]\n"
                + "para visualizar el plan de amortizacion para el interes\n"
                + "y periodos correspondientes a la celda elegida.";
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Instrucciones", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void jmItemAñosMesesActionPerformed(java.awt.event.ActionEvent evt) {
        Object item = evt.getSource();
        String tituloMarco;
        if (item == jmItemAños) {
            jmItemAños.setEnabled(false);
            jmItemMeses.setEnabled(true);
            tituloMarco = "Años del prestamo";
        } else {
            jmItemAños.setEnabled(true);
            jmItemMeses.setEnabled(false);
            tituloMarco = "Meses del prestamo";
        }
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(tituloMarco));
        jPanel1.repaint();
    }

    private void jmItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {
        String mensaje = "Aplicacion Prestamo. Version 1.0\nCopyright (c) Diego Chocochic, 2026";
        javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Acerca de Prestamo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void initTable(final int filasTabla, final int colsTabla) {
        class CModeloTablaPrestamo extends javax.swing.table.AbstractTableModel {
            Object dato[][] = new Object[filasTabla][colsTabla];
            String cabecera[] = new String[colsTabla];
            boolean editColum[] = new boolean[colsTabla];

            CModeloTablaPrestamo() {
                for (int c = 0; c < colsTabla; ++c) {
                    cabecera[c] = "Columna " + c;
                    if (c != 0) editColum[c] = true;
                }
            }

            public int getColumnCount() { return cabecera.length; }
            public int getRowCount() { return dato.length; }
            public String getColumnName(int col) { return cabecera[col]; }
            public Object getValueAt(int fila, int col) { return dato[fila][col]; }

            public void setValueAt(Object obj, int fila, int col) {
                dato[fila][col] = obj;
                fireTableCellUpdated(fila, col);
            }

            public boolean isCellEditable(int indFila, int indColum) { return editColum[indColum]; }
        }

        javax.swing.table.TableModel modeloTabla = new CModeloTablaPrestamo();

        javax.swing.table.TableColumnModel modeloColums = new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;
            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) { primeraCol = false; return; }
                super.addColumn(col);
            }
        };

        javax.swing.table.TableColumnModel modeloCabsFilas = new javax.swing.table.DefaultTableColumnModel() {
            boolean primeraCol = true;
            public void addColumn(javax.swing.table.TableColumn col) {
                if (primeraCol) {
                    col.setMaxWidth(55);
                    super.addColumn(col);
                    primeraCol = false;
                }
            }
        };

        jtablaPrestamo = new javax.swing.JTable(modeloTabla, modeloColums);
        jtablaPrestamo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtablaPrestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablaPrestamoMouseClicked(evt);
            }
        });

        jtablaCabsFilas = new javax.swing.JTable(modeloTabla, modeloCabsFilas);

        // Crear las columnas (sin esto, modeloColums/modeloCabsFilas quedan
        // vacíos porque al pasar un TableColumnModel propio, JTable deja de
        // crearlas automáticamente) — causaba ArrayIndexOutOfBoundsException
        // al hacer setValueAt sobre una tabla sin columnas.
        jtablaPrestamo.createDefaultColumnsFromModel();
        jtablaCabsFilas.createDefaultColumnsFromModel();

        jtablaPrestamo.setSelectionModel(jtablaCabsFilas.getSelectionModel());
        jtablaCabsFilas.setBackground(java.awt.Color.lightGray);
        jtablaCabsFilas.setSelectionBackground(java.awt.Color.lightGray);
        jtablaCabsFilas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtablaPrestamo.setFont(new java.awt.Font("Courier New", 0, 12));
        jtablaCabsFilas.setFont(new java.awt.Font("Courier New", 0, 12));

        jScrollPane1.setViewportView(jtablaPrestamo);

        // No usar setRowHeaderView(jtablaCabsFilas) directo: al ser un JTable
        // (Scrollable), JViewport calcula su tamaño preferido de forma que
        // termina reclamando casi todo el ancho del JScrollPane y deja la
        // tabla principal con ancho 0. Hay que envolverlo en un JViewport
        // propio con el tamaño fijado explícitamente (igual que hace el libro).
        javax.swing.JViewport jv = new javax.swing.JViewport();
        jv.setView(jtablaCabsFilas);
        jv.setPreferredSize(jtablaCabsFilas.getMaximumSize());
        jScrollPane1.setRowHeader(jv);
    }

    private void jbtCalculoPagosActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            credito = Double.parseDouble(jtfCredito.getText());
            periodoMin = Integer.parseInt(jtfPeriodoMin.getText());
            periodoMax = Integer.parseInt(jtfPeriodoMax.getText());
            interesMin = Double.parseDouble(jtfInteresMin.getText());
            interesMax = Double.parseDouble(jtfInteresMax.getText());
            incremento = Double.parseDouble((String) jcbIncremento.getSelectedItem());
            if (credito <= 0 || periodoMin <= 0 || periodoMax <= 0 || periodoMax < periodoMin
                    || interesMin < 0 || interesMax < 0 || interesMax < interesMin || incremento <= 0)
                throw new NumberFormatException();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(null, "Datos no validos", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        tiposIntrs = (int) ((interesMax - interesMin) / incremento) + 1;
        añosMeses = (periodoMax - periodoMin) + 1;

        int filas = tiposIntrs, cols = añosMeses;
        if (tiposIntrs < 18) filas = 18;
        if (añosMeses < 4) cols = 4;

        initTable(filas, cols + 1);

        for (int fila = 0; fila < tiposIntrs; ++fila)
            jtablaCabsFilas.setValueAt(AlinDer("##0.00", interesMin + incremento * fila) + "%", fila, 0);

        javax.swing.table.TableColumn colum;
        String per = (!jmItemAños.isEnabled()) ? " años" : " meses";
        for (int columna = 0; columna < añosMeses; ++columna) {
            colum = jtablaPrestamo.getColumnModel().getColumn(columna);
            colum.setHeaderValue((periodoMin + columna) + per);
        }

        int P = (!jmItemAños.isEnabled()) ? 12 : 1;

        double interes = 0.0, pago = 0.0;
        int meses;
        for (int fila = 0; fila < tiposIntrs; ++fila) {
            String sinteres = jtablaCabsFilas.getValueAt(fila, 0).toString();
            sinteres = sinteres.substring(0, sinteres.indexOf('%'));
            sinteres = sinteres.replace(',', '.').trim();
            interes = Double.parseDouble(sinteres);
            interes = interes / 100 / 12;

            for (int columna = 0; columna < añosMeses; ++columna) {
                colum = jtablaPrestamo.getColumnModel().getColumn(columna);
                String smeses = (String) colum.getHeaderValue();
                smeses = smeses.substring(0, smeses.indexOf(' '));
                meses = Integer.parseInt(smeses) * P;

                if (interes == 0.0)
                    pago = credito / meses;
                else
                    pago = credito * (interes / (1 - (1 / Math.pow(1.0 + interes, (double) meses))));

                jtablaPrestamo.setValueAt(AlinDer("###,###.00", pago), fila, columna);
            }
        }

        tablaPagos = true;
        jbtCalculoAmort.setEnabled(false);
    }

    private void jtablaPrestamoMouseClicked(java.awt.event.MouseEvent evt) {
        if (jtablaPrestamo.getSelectedRow() < 0 || jtablaPrestamo.getSelectedColumn() < 0) return;

        Object datoCelda = jtablaPrestamo.getValueAt(jtablaPrestamo.getSelectedRow(), jtablaPrestamo.getSelectedColumn());

        if (datoCelda != null && tablaPagos) {
            StringBuffer s = new StringBuffer(datoCelda.toString().trim());
            for (int i = 0; i < s.length(); ++i) {
                if (s.charAt(i) == ',') { s.delete(i, i + 1); --i; }
            }
            try {
                pagoMensual = Double.parseDouble(s.toString());
                jbtCalculoAmort.setEnabled(true);
            } catch (NumberFormatException e) {
                jbtCalculoAmort.setEnabled(false);
            }
        }
    }

    private void jbtCalculoAmortActionPerformed(java.awt.event.ActionEvent evt) {
        int fila = jtablaPrestamo.getSelectedRow();
        int columna = jtablaPrestamo.getSelectedColumn();

        String sinteres = (String) jtablaCabsFilas.getValueAt(fila, 0);
        sinteres = sinteres.substring(0, sinteres.indexOf('%'));
        sinteres = sinteres.replace(',', '.').trim();
        double interes = Double.parseDouble(sinteres) / 100 / 12;

        int P = (!jmItemAños.isEnabled()) ? 12 : 1;

        javax.swing.table.TableColumn colum = jtablaPrestamo.getColumnModel().getColumn(columna);
        String smeses = (String) colum.getHeaderValue();
        smeses = smeses.substring(0, smeses.indexOf(' '));
        int meses = Integer.parseInt(smeses) * P;

        int filas = meses, cols = 5;
        if (filas < 18) filas = 18;

        initTable(filas, cols);

        for (int mes = 0; mes < meses; ++mes)
            jtablaCabsFilas.setValueAt(AlinDer("####", mes + 1).toString(), mes, 0);

        String cab[] = { "Capital", "Intereses", "Capital pendiente", "Total intereses" };
        for (int c = 0; c < 4; ++c) {
            colum = jtablaPrestamo.getColumnModel().getColumn(c);
            colum.setHeaderValue(cab[c]);
        }

        double interesesMensuales, creditoPendiente = credito, totalIntereses = 0.0;
        double capitalMensualAmort;
        String formato = "###,###.00";

        for (int mes = 0; mes < meses; ++mes) {
            interesesMensuales = creditoPendiente * interes;
            capitalMensualAmort = pagoMensual - interesesMensuales;
            creditoPendiente -= capitalMensualAmort;
            totalIntereses += interesesMensuales;

            jtablaPrestamo.setValueAt(AlinDer(formato, capitalMensualAmort), mes, 0);
            jtablaPrestamo.setValueAt(AlinDer(formato, interesesMensuales), mes, 1);
            jtablaPrestamo.setValueAt(AlinDer(formato, creditoPendiente), mes, 2);
            jtablaPrestamo.setValueAt(AlinDer(formato, totalIntereses), mes, 3);
        }

        jbtCalculoAmort.setEnabled(false);
        tablaPagos = false;
    }

    private StringBuffer AlinDer(String patron, double dato) {
        java.text.FieldPosition fp = new java.text.FieldPosition(java.text.NumberFormat.FRACTION_FIELD);
        java.text.DecimalFormat formato = new java.text.DecimalFormat(patron,
                java.text.DecimalFormatSymbols.getInstance(java.util.Locale.US));
        StringBuffer salida = new StringBuffer();
        formato.format(dato, salida, fp);
        for (int i = 0; i < (patron.length() - salida.length()); i++)
            salida.insert(0, ' ');
        return salida;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PrestamoX().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtCalculoAmort;
    private javax.swing.JButton jbtCalculoPagos;
    private javax.swing.JComboBox<String> jcbIncremento;
    private javax.swing.JMenuItem jmItemAcercaDe;
    private javax.swing.JMenuItem jmItemAños;
    private javax.swing.JMenuItem jmItemInstruc;
    private javax.swing.JMenuItem jmItemMeses;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuBar jmbarBarraDeMenus;
    private javax.swing.JMenu jmnuAyuda;
    private javax.swing.JMenu jmnuOpciones;
    private javax.swing.JMenu jmnuPrestamoEn;
    private javax.swing.JTextField jtfCredito;
    private javax.swing.JTextField jtfInteresMax;
    private javax.swing.JTextField jtfInteresMin;
    private javax.swing.JTextField jtfPeriodoMax;
    private javax.swing.JTextField jtfPeriodoMin;
    // End of variables declaration//GEN-END:variables
}