
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JTable;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USUARIO
 */
public class jfrmPlanilla extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(jfrmPlanilla.class.getName());
    
    DefaultTableModel modelo = new DefaultTableModel();
    String[] columnas = {"DPI", "NOMBRE", "APELLIDO", "SALARIO", "CATEGORÍA", "PUESTO", "TOTAL"};
    
    double salario, CatA = 500, CatB = 350, CatC = 150, total;

    /**
     * Creates new form jfrmPlanilla
     */
    public jfrmPlanilla() {
        initComponents();
        this.setTitle("Panilla 2026");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        modelo.setColumnIdentifiers(columnas);
        jtabDatos.setModel(modelo);
    }
    
    public void totalSalario()
    {
        salario = Double.parseDouble(jtxtSalario.getText());
        if (jcbxCategoria.getSelectedItem().equals("A"))
            total = salario + CatA;
        else if (jcbxCategoria.getSelectedItem().equals("B"))
            total = salario + CatB;
        else if (jcbxCategoria.getSelectedItem().equals("C"))
            total = salario + CatC;
        else
            total = salario;
    }
    
    public void limpiarCajas()
    {
        jtxtDPI.setText("");
        jtxtNombre.setText("");
        jtxtApellido.setText("");
        jtxtSalario.setText("");
        jcbxCategoria.setSelectedItem("Seleccione Categoría");
        jcbxPuesto.setSelectedItem("Seleccione Puesto");
        jtxtDPI.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtDPI = new javax.swing.JTextField();
        jtxtNombre = new javax.swing.JTextField();
        jtxtApellido = new javax.swing.JTextField();
        jtxtSalario = new javax.swing.JTextField();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jcbxPuesto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtabDatos = new javax.swing.JTable();
        jbtnInsertar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnEditar = new javax.swing.JButton();
        jbtnImprimir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("PLANILLA");

        jLabel2.setText("DPI:");

        jLabel3.setText("NOMBRE:");

        jLabel4.setText("APELLIDOS:");

        jLabel5.setText("SALARIO:");

        jLabel6.setText("CATEGORÍA:");

        jLabel7.setText("PUESTO:");

        jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Categoría", "A", "B", "C" }));

        jcbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Puesto", "Ingeniero", "Contador", "Jefe", "Supervisor" }));

        jtabDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtabDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtabDatosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtabDatos);

        jbtnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnInsertar.setText("INSERTAR");
        jbtnInsertar.addActionListener(this::jbtnInsertarActionPerformed);

        jbtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.addActionListener(this::jbtnEliminarActionPerformed);

        jbtnEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnEditar.setText("EDITAR");
        jbtnEditar.addActionListener(this::jbtnEditarActionPerformed);

        jbtnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnImprimir.setText("IMPRIMIR");
        jbtnImprimir.addActionListener(this::jbtnImprimirActionPerformed);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Diego Alejandro Chocochic L. IV Bach. \"C\" clave:6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnEliminar))
                    .addComponent(jbtnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbxCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtSalario)
                                    .addComponent(jcbxPuesto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtxtApellido)
                                    .addComponent(jtxtNombre)
                                    .addComponent(jtxtDPI)))
                            .addComponent(jLabel1)
                            .addComponent(jbtnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel8)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnImprimir)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtxtDPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jcbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jcbxPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnInsertar)
                            .addComponent(jbtnEliminar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnEditar)
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInsertarActionPerformed
        // TODO add your handling code here:
        totalSalario();
        modelo.addRow(new Object[]
        {
            jtxtDPI.getText(),
            jtxtNombre.getText(),
            jtxtApellido.getText(),
            jtxtSalario.getText(),
            jcbxCategoria.getSelectedItem(),
            jcbxPuesto.getSelectedItem(),
            total
        }        
        );
        limpiarCajas();
    }//GEN-LAST:event_jbtnInsertarActionPerformed

    private void jtabDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtabDatosMousePressed
        // TODO add your handling code here:
        int fila = jtabDatos.getSelectedRow();
        jtxtDPI.setText(jtabDatos.getValueAt(fila, 0).toString());
        jtxtNombre.setText(jtabDatos.getValueAt(fila, 1).toString());
        jtxtApellido.setText(jtabDatos.getValueAt(fila, 2).toString());
        jtxtSalario.setText(jtabDatos.getValueAt(fila, 3).toString());
        jcbxCategoria.setSelectedItem(jtabDatos.getValueAt(fila, 4));
        jcbxPuesto.setSelectedItem(jtabDatos.getValueAt(fila, 5));
    }//GEN-LAST:event_jtabDatosMousePressed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        if(modelo.getRowCount() <= 0)
            JOptionPane.showMessageDialog(null, "¡No hay registros!", "Alerta", JOptionPane.WARNING_MESSAGE);
        else
        {
            modelo.removeRow(jtabDatos.getSelectedRow());
            JOptionPane.showMessageDialog(null, "¡Registro elimindo!", "Completado", JOptionPane.INFORMATION_MESSAGE);
            limpiarCajas();
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditarActionPerformed
        // TODO add your handling code here:
        int fila = jtabDatos.getSelectedRow();
        modelo.setValueAt(jtxtDPI.getText(), fila, 0);
        modelo.setValueAt(jtxtNombre.getText(), fila, 1);
        modelo.setValueAt(jtxtApellido.getText(), fila, 2);
        modelo.setValueAt(jtxtSalario.getText(), fila, 3);
        modelo.setValueAt(jcbxCategoria.getSelectedItem(), fila, 4);
        modelo.setValueAt(jcbxPuesto.getSelectedItem(), fila, 5);
        totalSalario();
        modelo.setValueAt(total, fila, 6);
        limpiarCajas();
    }//GEN-LAST:event_jbtnEditarActionPerformed

    private void jbtnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnImprimirActionPerformed
        // TODO add your handling code here:
        MessageFormat Header = new MessageFormat("Planilla 2026");
        MessageFormat Footer = new MessageFormat("Página {0}");
        try{
            PrintRequestAttributeSet set = new HashPrintRequestAttributeSet();
            set.add(OrientationRequested.LANDSCAPE);
            jtabDatos.print(JTable.PrintMode.FIT_WIDTH, Header, Footer, true, set, true);
            JOptionPane.showMessageDialog(null, "\n ¡Impreso con éxito!", "Completado", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (java.awt.print.PrinterException e){
            JOptionPane.showMessageDialog(null, "\n¡Fallido!\n" + e, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new jfrmPlanilla().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEditar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnImprimir;
    private javax.swing.JButton jbtnInsertar;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxPuesto;
    private javax.swing.JTable jtabDatos;
    private javax.swing.JTextField jtxtApellido;
    private javax.swing.JTextField jtxtDPI;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtSalario;
    // End of variables declaration//GEN-END:variables
}
